### ISSUE TITLE
similar projects

### ISSUE THREAD

**Issue by 1u** [TransitionZH/green#1]
## the-ecomap
http://the-ecomap.com/#

## opengreenmap
ex: http://www.opengreenmap.org/greenmap/nyc-energy, and here is [the orga behind](http://www.greenmapnyc.org/)
- Categories give colours and almost endless subcategories give icons
- Printable map [example](http://www.greenmapnyc.org/resources/uploads/embeds/files/Lower_East_Ride_GreenMap.pdf)

**Comment by artemi-egorov** [comment]
Moved to Trello: https://trello.com/b/PVb1WBBP/andere-netzwerk
